"""drop ip_hash from sessions

Revision ID: 0717a49766f6
Revises: e3d4ac06dddd
Create Date: 2026-05-01 11:24:21.690453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0717a49766f6'
down_revision: Union[str, None] = 'e3d4ac06dddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'ip_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('ip_hash', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
