"""add emotion_answer to answers

Revision ID: 081d8e7d79be
Revises: 96d545860ba6
Create Date: 2026-06-14 10:08:45.845090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081d8e7d79be'
down_revision: Union[str, None] = '96d545860ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('emotion_answer', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'emotion_answer')
    # ### end Alembic commands ###
