"""add metadata columns to interviews

Revision ID: 2e5a7415da74
Revises: 2e31ee56595e
Create Date: 2026-06-07 16:27:05.984090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5a7415da74'
down_revision: Union[str, None] = '2e31ee56595e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('format_type', sa.String(length=50), nullable=True))
    op.add_column('interviews', sa.Column('organized_by', sa.String(length=100), nullable=True))
    op.add_column('interviews', sa.Column('host_or_interviewer', sa.String(length=100), nullable=True))
    op.add_column('interviews', sa.Column('participants', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'participants')
    op.drop_column('interviews', 'host_or_interviewer')
    op.drop_column('interviews', 'organized_by')
    op.drop_column('interviews', 'format_type')
    # ### end Alembic commands ###
