"""add fields negative_pole_name, negative_pole_description, positive_pole_name and positive_pole_description

Revision ID: 51c9fb4e4f9d
Revises: ef8c8faf51b7
Create Date: 2026-05-09 22:43:55.157186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c9fb4e4f9d'
down_revision: Union[str, None] = 'ef8c8faf51b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('negative_pole_name', sa.String(length=64), nullable=False))
    op.add_column('categories', sa.Column('negative_pole_description', sa.Text(), nullable=False))
    op.add_column('categories', sa.Column('positive_pole_name', sa.String(length=64), nullable=False))
    op.add_column('categories', sa.Column('positive_pole_description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'positive_pole_description')
    op.drop_column('categories', 'positive_pole_name')
    op.drop_column('categories', 'negative_pole_description')
    op.drop_column('categories', 'negative_pole_name')
    # ### end Alembic commands ###
