"""answers replace visitor_id with test_attempt_id

Revision ID: 7468a0f4917a
Revises: 3a10a756b02f
Create Date: 2026-05-01 13:15:24.958012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7468a0f4917a'
down_revision: Union[str, None] = '3a10a756b02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('test_attempt_id', sa.Integer(), nullable=False))
    op.drop_constraint('answers_ibfk_3', 'answers', type_='foreignkey')
    op.drop_index('ix_answers_visitor_id', table_name='answers')
    op.create_index(op.f('ix_answers_test_attempt_id'), 'answers', ['test_attempt_id'], unique=False)
    op.create_foreign_key(None, 'answers', 'test_attempts', ['test_attempt_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answers', 'visitor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('visitor_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_ibfk_3', 'answers', 'visitors', ['visitor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_answers_test_attempt_id'), table_name='answers')
    op.create_index('ix_answers_visitor_id', 'answers', ['visitor_id'], unique=False)
    op.drop_column('answers', 'test_attempt_id')
    # ### end Alembic commands ###
