"""add description to questions

Revision ID: 76446176c32f
Revises: 081d8e7d79be
Create Date: 2026-06-15 17:18:48.455715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76446176c32f'
down_revision: Union[str, None] = '081d8e7d79be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'description')
    # ### end Alembic commands ###
