"""add axis_value to response_options

Revision ID: 7b7de73dccdf
Revises: f08afc05a8ad
Create Date: 2026-06-14 00:12:05.238094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7de73dccdf'
down_revision: Union[str, None] = 'f08afc05a8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_options', sa.Column('axis_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_options', 'axis_value')
    # ### end Alembic commands ###
