"""add summary memory fields to chats

Revision ID: 92bd9f90567b
Revises: 427c70690cd8
Create Date: 2026-06-11 22:46:35.894041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bd9f90567b'
down_revision: Union[str, None] = '427c70690cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('chats', sa.Column('last_summarized_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'last_summarized_message_id')
    op.drop_column('chats', 'summary')
    # ### end Alembic commands ###
