"""add uuid to test_attempts

Revision ID: ac47bd603a90
Revises: 7468a0f4917a
Create Date: 2026-05-01 18:29:49.748457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac47bd603a90'
down_revision: Union[str, None] = '7468a0f4917a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempts', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'test_attempts', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_attempts', type_='unique')
    op.drop_column('test_attempts', 'uuid')
    # ### end Alembic commands ###
