"""create visitors sessions events

Revision ID: ae95d511bf6b
Revises: 28f084649c34
Create Date: 2026-04-30 22:35:40.674239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae95d511bf6b'
down_revision: Union[str, None] = '28f084649c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('visitor_uid', sa.String(length=64), nullable=False),
    sa.Column('browser_name', sa.String(length=50), nullable=True),
    sa.Column('browser_version', sa.String(length=30), nullable=True),
    sa.Column('engine_name', sa.String(length=50), nullable=True),
    sa.Column('os_name', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=30), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('device_vendor', sa.String(length=50), nullable=True),
    sa.Column('device_model', sa.String(length=50), nullable=True),
    sa.Column('is_mobile', sa.Boolean(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('pixel_ratio', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('color_depth', sa.SmallInteger(), nullable=True),
    sa.Column('cpu_cores', sa.SmallInteger(), nullable=True),
    sa.Column('device_memory', sa.SmallInteger(), nullable=True),
    sa.Column('touch_support', sa.Boolean(), nullable=True),
    sa.Column('primary_language', sa.String(length=20), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('total_page_views', sa.Integer(), nullable=False),
    sa.Column('total_time_seconds', sa.Integer(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_at', sa.DateTime(), nullable=True),
    sa.Column('consent_version', sa.String(length=20), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visitor_uid')
    )
    op.create_index(op.f('ix_visitors_device_type'), 'visitors', ['device_type'], unique=False)
    op.create_index(op.f('ix_visitors_last_seen_at'), 'visitors', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_visitors_primary_language'), 'visitors', ['primary_language'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_uid', sa.String(length=36), nullable=False),
    sa.Column('visitor_id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('isp', sa.String(length=255), nullable=True),
    sa.Column('asn', sa.Integer(), nullable=True),
    sa.Column('is_vpn', sa.Boolean(), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('is_datacenter', sa.Boolean(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geo_accuracy', sa.String(length=20), nullable=True),
    sa.Column('viewport_width', sa.Integer(), nullable=True),
    sa.Column('viewport_height', sa.Integer(), nullable=True),
    sa.Column('connection_type', sa.String(length=20), nullable=True),
    sa.Column('connection_downlink', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('referer_domain', sa.String(length=255), nullable=True),
    sa.Column('landing_page', sa.Text(), nullable=True),
    sa.Column('exit_page', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_term', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=100), nullable=True),
    sa.Column('gclid', sa.String(length=255), nullable=True),
    sa.Column('fbclid', sa.String(length=255), nullable=True),
    sa.Column('page_views_count', sa.Integer(), nullable=False),
    sa.Column('events_count', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('is_bounce', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_uid')
    )
    op.create_index(op.f('ix_sessions_country_code'), 'sessions', ['country_code'], unique=False)
    op.create_index(op.f('ix_sessions_ip_address'), 'sessions', ['ip_address'], unique=False)
    op.create_index(op.f('ix_sessions_referer_domain'), 'sessions', ['referer_domain'], unique=False)
    op.create_index(op.f('ix_sessions_started_at'), 'sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_sessions_utm_source'), 'sessions', ['utm_source'], unique=False)
    op.create_index(op.f('ix_sessions_visitor_id'), 'sessions', ['visitor_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('visitor_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=True),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('page_path', sa.String(length=500), nullable=True),
    sa.Column('page_title', sa.String(length=255), nullable=True),
    sa.Column('element_tag', sa.String(length=50), nullable=True),
    sa.Column('element_id', sa.String(length=255), nullable=True),
    sa.Column('element_class', sa.String(length=255), nullable=True),
    sa.Column('element_text', sa.String(length=500), nullable=True),
    sa.Column('scroll_depth', sa.SmallInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_page_path'), 'events', ['page_path'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_index(op.f('ix_events_visitor_id'), 'events', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_visitor_id'), table_name='events')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_page_path'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_sessions_visitor_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_utm_source'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_started_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_referer_domain'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_ip_address'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_country_code'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_visitors_primary_language'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_last_seen_at'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_device_type'), table_name='visitors')
    op.drop_table('visitors')
    # ### end Alembic commands ###
