"""create candidates table

Revision ID: d1cdff828ab3
Revises: 
Create Date: 2026-04-30 21:16:53.627539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1cdff828ab3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('presidential_candidate', sa.String(length=255), nullable=False),
    sa.Column('vice_presidential_candidate', sa.String(length=255), nullable=False),
    sa.Column('political_group', sa.String(length=255), nullable=False),
    sa.Column('photo_of_political_group', sa.String(length=500), nullable=True),
    sa.Column('photo_president', sa.String(length=500), nullable=True),
    sa.Column('photo_vice_president', sa.String(length=500), nullable=True),
    sa.Column('troubles_questions', sa.Text(), nullable=True),
    sa.Column('political_spectrum', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    # ### end Alembic commands ###
