"""change field url

Revision ID: d4e711e3dfd9
Revises: e1c7349ae1f0
Create Date: 2026-05-17 20:15:16.610234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e711e3dfd9'
down_revision: Union[str, None] = 'e1c7349ae1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('government_plans', sa.Column('url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('government_plans', 'url')
    # ### end Alembic commands ###
