"""add image_url to tests

Revision ID: e0b6a8104499
Revises: 92bd9f90567b
Create Date: 2026-06-13 23:37:46.034641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b6a8104499'
down_revision: Union[str, None] = '92bd9f90567b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('image_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'image_url')
    # ### end Alembic commands ###
