"""change name fields

Revision ID: e1c7349ae1f0
Revises: c9842b9c6f26
Create Date: 2026-05-17 20:10:49.241315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1c7349ae1f0'
down_revision: Union[str, None] = 'c9842b9c6f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('tests', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('tests', 'descripcion')
    op.drop_column('tests', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('tests', sa.Column('descripcion', mysql.TEXT(), nullable=True))
    op.drop_column('tests', 'description')
    op.drop_column('tests', 'name')
    # ### end Alembic commands ###
