"""add fields proposal, confidence, reasoning, ambiguities, coder_type and coder_name

Revision ID: ef8c8faf51b7
Revises: ac47bd603a90
Create Date: 2026-05-09 21:14:39.383338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8c8faf51b7'
down_revision: Union[str, None] = 'ac47bd603a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postures', sa.Column('coder_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postures', 'coder_name')
    # ### end Alembic commands ###
