"""add type to tests

Revision ID: f08afc05a8ad
Revises: b7d9ede2ed53
Create Date: 2026-06-14 00:04:57.071504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08afc05a8ad'
down_revision: Union[str, None] = 'b7d9ede2ed53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('type', sa.Enum('POLITICAL_SPECTRUM', 'PROGRAMMATIC_ALIGNMENT', name='test_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'type')
    # ### end Alembic commands ###
