INSERT INTO candidates (
    presidential_candidate,
    vice_presidential_candidate,
    political_group,
    photo_of_political_group,
    photo_president,
    photo_vice_president,
    troubles_questions,
    political_spectrum,
    created_at,
    updated_at,
    deleted_at
) VALUES
('Óscar Mauricio Lizcano Arango', 'Pedro Luis de la Torre Márquez', 'Coalición F.A.M.I.L.I.A', 'https://img.luifereduardoo.com/elegio/Screenshot%202026-05-15%20213617.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Mauricio_Lizcano_2023.jpg/500px-Mauricio_Lizcano_2023.jpg', 'https://www.lapatria.com/sites/default/files/inline-images/Pedro-Luis-de-la-Torre-Marquez.jpg', 'Señalamientos periodísticos por presunto acoso sexual a una contratista. Salpicado por líos de tierras (despojo) en Risaralda. (Fuente: El Espectador / Vorágine).', 'Centro-Derecha', NOW(), NOW(), NULL),

('Raúl Santiago Botero Jaramillo', 'Carlos Fernando Cuevas Romero', 'Romper el sistema', 'https://santiagobotero.com/logo-romper-sistema.svg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Santiago_Botero_Jaramillo_retrato_oficial_%28cropped%29.webp/500px-Santiago_Botero_Jaramillo_retrato_oficial_%28cropped%29.webp.png', 'https://pbs.twimg.com/media/GX7MZydXYAAoPOT.jpg', 'No se le conocen cuestionamientos judiciales graves o líos legales masivos. (Fuente: Consulta abierta).', 'Centro', NOW(), NOW(), NULL),

('Miguel Uribe Londoño', 'Luisa Fernanda Villegas Araque', 'Partido Demócrata Colombiano', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Logo_Partido_Democrata_Colombiano_%28cropped%29.png/500px-Logo_Partido_Democrata_Colombiano_%28cropped%29.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Miguel_Uribe_Londo%C3%B1o_%28cropped%29.png/500px-Miguel_Uribe_Londo%C3%B1o_%28cropped%29.png', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8OjPIcOL-yz7kOc7qmzX3jYwd4Sx6vt2ZKQ&s', 'Cuestionamientos políticos por manejo de recursos en pandemia como Secretario de Gobierno y menciones en volteo de tierras, sin condenas vigentes. (Fuente: Cuestión Pública / La Silla Vacía).', 'Derecha', NOW(), NOW(), NULL),

('Sondra Macollins Garvin Pinto', 'Leonardo Karam Helo', 'Sondra Macollins, la abogada de hierro', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQYDYGiT8Cf_BBgG9h4zX0OhDC6z0a1i2LTPQJXLDBvnSVqyJrO', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Colombian_Presidential_Election_First_Round_Results%2C_2026.svg/500px-Colombian_Presidential_Election_First_Round_Results%2C_2026.svg.png', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTEh6Ee06tKD2E5uCTRF-FKk8ebYL1qle71Q&s', 'Abogada penalista que ha defendido a narcotraficantes extraditables y exjefes paramilitares (''Macaco''). Criticada por los nexos de sus clientes. (Fuente: Revista Semana / W Radio).', 'Derecha', NOW(), NOW(), NULL),

('Iván Cepeda Castro', 'Aída Marina Quilcué Vivas', 'Movimiento Político Pacto Histórico', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Pacto_Hist%C3%B3rico_Logo_Oficial.png/500px-Pacto_Hist%C3%B3rico_Logo_Oficial.png', 'https://upload.wikimedia.org/wikipedia/commons/5/58/Perfil_Iv%C3%A1n_Cepeda_%28cropped%29.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Aida_Quilcu%C3%A9_2024.jpg/500px-Aida_Quilcu%C3%A9_2024.jpg', 'Denunciado por manipulación de testigos (caso Uribe, declarado víctima). Salpicado por correos encontrados en los computadores del jefe guerrillero Raúl Reyes (FARC) que sugerían nexos, aunque la Corte Suprema invalidó las pruebas. (Fuente: Corte Suprema / Revista Semana).', 'Izquierda', NOW(), NOW(), NULL),

('Abelardo Gabriel de la Espriella', 'José Manuel Restrepo Abondano', 'Defensores de la patria', 'https://defensoresdelapatria.com/wp-content/uploads/2025/03/4-e1744391302884-1.png', 'https://d2gjqh9j26unp0.cloudfront.net/profilepic/4a8556fa85aca59851e88e55126034a6', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Jos%C3%A9_Manuel_Restrepo.jpg/500px-Jos%C3%A9_Manuel_Restrepo.jpg', 'Criticado éticamente por defender judicialmente a clientes polémicos (David Murcia Guzmán en DMG, Alex Saab, paramilitares y exmagistrados corruptos). (Fuente: La Silla Vacía / Noticias Caracol).', 'Derecha', NOW(), NOW(), NULL),

('Claudia Nayibe López Hernández', 'Leonardo Humberto Huerta Gutiérrez', 'Con Claudia imparables', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrp8lF1hJd09VhwPWCICrwNRG3GJtlupd__w&s', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Claudia_Lopez_H_26.jpg/500px-Claudia_Lopez_H_26.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyneFSmpJ1jQiZ7SpFvpSC_RjZjsovgPemEA&s', 'Indagaciones preliminares en Fiscalía por presuntas irregularidades de contratación en pandemia y controversias de la Alcaldía de Bogotá. (Fuente: El Tiempo / Fiscalía General).', 'Centro-Izquierda', NOW(), NOW(), NULL),

('Paloma Susana Valencia Laserna', 'Juan Daniel Oviedo Arango', 'Partido Centro Democrático', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Partido_Centro_Democr%C3%A1tico_Registradur%C3%ADa.png/500px-Partido_Centro_Democr%C3%A1tico_Registradur%C3%ADa.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Discurosdepoposicion_%28cropped%29.jpg/500px-Discurosdepoposicion_%28cropped%29.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Juan_Daniel_Oviedo_2025.jpg/500px-Juan_Daniel_Oviedo_2025.jpg', 'Investigada preliminarmente por la Corte Suprema en el ''Cartel de la Toga'' (archivado a su favor). Críticas por propuestas de dividir el departamento del Cauca. (Fuente: Corte Suprema / El Espectador).', 'Derecha', NOW(), NOW(), NULL),

('Sergio Fajardo Valderrama', 'Edna Cristina del Socorro Bonilla Seba', 'Partido político Dignidad & Compromiso', 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTtn_6JdLwREl8Ub1K7Zaa6igDIAZhRuYKawaWFBbVWQBk9JWNY', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/SergioFajardo.jpg/500px-SergioFajardo.jpg', 'https://www.uexternado.edu.co/wp-content/uploads/2022/10/edna-cristina-bonilla.jpg', 'Imputado y absuelto por préstamo en dólares durante su gobernación. Fallado con responsabilidad fiscal (luego absuelto) por Hidroituango. (Fuente: Fiscalía General / Contraloría).', 'Centro', NOW(), NOW(), NULL),

('Roy Leonardo Barreras Montealegre', 'Martha Lucía Zamora Ávila', 'Partido político La Fuerza', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ8SZPDMB4PsavMjgladSRKY1DwHBd4G2UZoIz23NNtILMv44WW', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/20250609_Comision_Procesos_Electorales-Juan_Cano01043.jpg/500px-20250609_Comision_Procesos_Electorales-Juan_Cano01043.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/MarthaZamora.jpg/500px-MarthaZamora.jpg', 'Su elección al Senado fue anulada por doble militancia (2023). Grabado en los ''Petrovideos'' dirigiendo estrategias polémicas de campaña sucia. (Fuente: Consejo de Estado / Revista Semana).', 'Centro', NOW(), NOW(), NULL),

('Gustavo Matamoros Camacho', 'Mila María Paz Campaz', 'Partido Ecologista Colombiano', 'https://www.partidoecologista.org/assets/PartidoEcologistaCol-5a087e27c361b5b948777b83295874c4f06658859136f02ebbeaf137dac07c97.webp', 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Gustavo_Matamoros_Camacho.png', 'https://www.lapatria.com/sites/default/files/inline-images/Mila-MarIa-Paz.jpeg', 'Llamado a calificar servicios como General en medio de choques internos con la cúpula militar y acusaciones mutuas de malos manejos. Sin condenas penales. (Fuente: Revista Semana / El Tiempo).', 'Derecha', NOW(), NOW(), NULL),

('Luis Gilberto Murillo Urrutia', 'Luz María Zapata Zapata', 'Luis Gilberto soy yo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7hmJR2hZvSMiy17YLJr__yrhelmULjcAB8BgO_B_-nfDQ3kMX', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/20240521_posesi%C3%B3n_canciller_Murillo-Joel_Gonz%C3%A1lez1536_%28Cropped%29.jpg/500px-20240521_posesi%C3%B3n_canciller_Murillo-Joel_Gonz%C3%A1lez1536_%28Cropped%29.jpg', 'https://www.wradio.com.co/resizer/v2/2KYWE4Z7NZGTRLSH7WCWCK525M.jpeg?auth=1eceabb294d3ee9fcc4f508f46164497535f78338083be6517dfc70e986a0b73&quality=70&width=1200&height=900&smart=true', 'Condenado a 6 meses de cárcel en 1997 por peculado por destinación oficial diferente (reparación de escuela). La justicia le devolvió sus derechos políticos después. (Fuente: Corte Suprema / Consejo de Estado).', 'Centro-Izquierda', NOW(), NOW(), NULL),

('Carlos Eduardo Caicedo Omar', 'Nelson Javier Alarcón Suárez', 'Caicedo', 'https://equipodevoceros.caicedopresidente.com.co/CAICEDO-PRESIDENTE-BLANCO.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Carlos_Caicedo_%28cropped%29.jpg/500px-Carlos_Caicedo_%28cropped%29.jpg', 'https://lh5.googleusercontent.com/proxy/ptChFFgD981vU5HRNP__LX4zuO2qauAgh_W2mf2v94m_pa34NySTuScN0zU2HqEk_gzLAOh5YDGqpU8mn_8hZLmg42OJMbX3lmsAHRgQxZHZjhAuhgjuMzTN8z6D2-KRuDL20QB6waYESAWNruw9ZNiS2yOt', 'Investigado y llamado a juicio por la Fiscalía por delitos de peculado en las obras inconclusas de los Juegos Bolivarianos y megabibliotecas en Santa Marta. (Fuente: Fiscalía General de la Nación).', 'Izquierda', NOW(), NOW(), NULL);